package com.xing.wanandroid.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import java.util.List;

import com.xing.wanandroid.db.bean.User;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER".
*/
public class UserDao extends AbstractDao<User, String> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Admin = new Property(0, boolean.class, "admin", false, "ADMIN");
        public final static Property CollectionIds = new Property(1, String.class, "collectionIds", false, "COLLECTION_IDS");
        public final static Property Email = new Property(2, String.class, "email", false, "EMAIL");
        public final static Property Icon = new Property(3, String.class, "icon", false, "ICON");
        public final static Property Id = new Property(4, int.class, "id", false, "ID");
        public final static Property Nickname = new Property(5, String.class, "nickname", false, "NICKNAME");
        public final static Property Password = new Property(6, String.class, "password", false, "PASSWORD");
        public final static Property PublicName = new Property(7, String.class, "publicName", false, "PUBLIC_NAME");
        public final static Property Token = new Property(8, String.class, "token", false, "TOKEN");
        public final static Property Type = new Property(9, int.class, "type", false, "TYPE");
        public final static Property Username = new Property(10, String.class, "username", true, "USERNAME");
    }

    private final IntConverter collectionIdsConverter = new IntConverter();

    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER\" (" + //
                "\"ADMIN\" INTEGER NOT NULL ," + // 0: admin
                "\"COLLECTION_IDS\" TEXT," + // 1: collectionIds
                "\"EMAIL\" TEXT," + // 2: email
                "\"ICON\" TEXT," + // 3: icon
                "\"ID\" INTEGER NOT NULL ," + // 4: id
                "\"NICKNAME\" TEXT," + // 5: nickname
                "\"PASSWORD\" TEXT," + // 6: password
                "\"PUBLIC_NAME\" TEXT," + // 7: publicName
                "\"TOKEN\" TEXT," + // 8: token
                "\"TYPE\" INTEGER NOT NULL ," + // 9: type
                "\"USERNAME\" TEXT PRIMARY KEY NOT NULL );"); // 10: username
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getAdmin() ? 1L: 0L);
 
        List collectionIds = entity.getCollectionIds();
        if (collectionIds != null) {
            stmt.bindString(2, collectionIdsConverter.convertToDatabaseValue(collectionIds));
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(3, email);
        }
 
        String icon = entity.getIcon();
        if (icon != null) {
            stmt.bindString(4, icon);
        }
        stmt.bindLong(5, entity.getId());
 
        String nickname = entity.getNickname();
        if (nickname != null) {
            stmt.bindString(6, nickname);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(7, password);
        }
 
        String publicName = entity.getPublicName();
        if (publicName != null) {
            stmt.bindString(8, publicName);
        }
 
        String token = entity.getToken();
        if (token != null) {
            stmt.bindString(9, token);
        }
        stmt.bindLong(10, entity.getType());
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(11, username);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getAdmin() ? 1L: 0L);
 
        List collectionIds = entity.getCollectionIds();
        if (collectionIds != null) {
            stmt.bindString(2, collectionIdsConverter.convertToDatabaseValue(collectionIds));
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(3, email);
        }
 
        String icon = entity.getIcon();
        if (icon != null) {
            stmt.bindString(4, icon);
        }
        stmt.bindLong(5, entity.getId());
 
        String nickname = entity.getNickname();
        if (nickname != null) {
            stmt.bindString(6, nickname);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(7, password);
        }
 
        String publicName = entity.getPublicName();
        if (publicName != null) {
            stmt.bindString(8, publicName);
        }
 
        String token = entity.getToken();
        if (token != null) {
            stmt.bindString(9, token);
        }
        stmt.bindLong(10, entity.getType());
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(11, username);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.getShort(offset + 0) != 0, // admin
            cursor.isNull(offset + 1) ? null : collectionIdsConverter.convertToEntityProperty(cursor.getString(offset + 1)), // collectionIds
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // email
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // icon
            cursor.getInt(offset + 4), // id
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // nickname
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // password
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // publicName
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // token
            cursor.getInt(offset + 9), // type
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // username
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setAdmin(cursor.getShort(offset + 0) != 0);
        entity.setCollectionIds(cursor.isNull(offset + 1) ? null : collectionIdsConverter.convertToEntityProperty(cursor.getString(offset + 1)));
        entity.setEmail(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIcon(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setId(cursor.getInt(offset + 4));
        entity.setNickname(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPassword(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPublicName(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setToken(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setType(cursor.getInt(offset + 9));
        entity.setUsername(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    @Override
    protected final String updateKeyAfterInsert(User entity, long rowId) {
        return entity.getUsername();
    }
    
    @Override
    public String getKey(User entity) {
        if(entity != null) {
            return entity.getUsername();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User entity) {
        return entity.getUsername() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
